### ISSUE TITLE
Cannot figure out pippin-launch errors

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#137]
On perlmutter@Nersc, please try

cd $SNANA_LSST_USERS/ayanmitr/PIPPIN_PHOTOZ+CC
pippin.sh lsst_combined_CC.yml -c

There are several error messages starting with "No external match ...", but we can't tell if this is just a warning or a fatal error. The other error results in a  traceback.

**Comment by OmegaLambda1998** [comment]
So, what's happening with the external match is the external LCFIT task name does not match this jobs LCFIT task name (LOWZ_DC2LOWZ_BIASCOR != FIT_DC2LOWZ_BIASCOR). You need to add an EXTERNAL_MAP key to let pippin know what directory maps to what task. This is because LCFIT can have multiple tasks under the same name, since the task that actually runs is LCFIT_SIM.

```
FIT_DC2LOWZ_BIASCOR:
    ...
    EXTERNAL_DIRS:
        - $PIPPIN_OUTPUT/LSST_BIASCOR/2_LCFIT/LOWZ_DC2LOWZ_BIASCOR
        
    EXTERNAL_MAP:
        FIT_DC2LOWZ_BIASCOR_DC2LOWZ_BIASCOR: LOWZ_DC2LOWZ_BIASCOR
```

Not including this shouldn't stop Pippin, but it will mean that task is rerun instead of using the external task.
